import { ArrowLeft, ClipboardCheck, FileText, Save } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useForm } from 'react-hook-form'
import { useNavigate, useParams } from 'react-router-dom'
import { useToast } from '../../../components/common/Toaster'
import { APP_ROUTES } from '../../../constants/routes'
import { fetchVisaRequirementById, fetchVisaTypeOptions, visaRequirementsApi } from '../service/visaRequirementsService'
import { buildVisaRequirementPayload, toVisaRequirementValues } from '../utils/visaRequirementsUtils'

const initialValues = { visa_type_id: '', document_name: '', instructions: '', is_required: true, allow_multiple: false, sort_order: 0 }
const optionLabel = (type) => type.country_name ? `${type.country_name} — ${type.visa_name || type.visa_title}` : (type.visa_name || type.visa_title || `Visa type ${type.id}`)

export default function VisaRequirementFormPage({ action }) {
  const edit = action === 'update'
  const { id } = useParams()
  const navigate = useNavigate()
  const toast = useToast()
  const [visaTypes, setVisaTypes] = useState([])
  const [loading, setLoading] = useState(edit)
  const { register, reset, handleSubmit, formState: { errors, isSubmitting } } = useForm({ defaultValues: initialValues })
  useEffect(() => { let active = true; (async () => { try { const [types, requirement] = await Promise.all([fetchVisaTypeOptions(), edit ? fetchVisaRequirementById(id) : Promise.resolve(null)]); if (!active) return; setVisaTypes(types); if (requirement) reset(toVisaRequirementValues(requirement)) } catch (error) { toast.error(error.message || 'Unable to load form data.'); if (edit) navigate(APP_ROUTES.visaRequirements) } finally { if (active) setLoading(false) } })(); return () => { active = false } }, [edit, id, navigate, reset, toast])
  const submit = async (values) => { try { const payload = buildVisaRequirementPayload(values); if (edit) await visaRequirementsApi.update(id, payload); else await visaRequirementsApi.create(payload); toast.success(`Visa requirement ${edit ? 'updated' : 'created'} successfully.`); navigate(APP_ROUTES.visaRequirements) } catch (error) { toast.error(error.message || 'Unable to save visa requirement.') } }
  return <main className="routes-page"><div className="routes-page__inner max-w-5xl"><header className="routes-page__header"><button type="button" className="mb-4 inline-flex items-center gap-2 text-sm font-semibold text-[#8fa0bd] hover:text-white" onClick={() => navigate(APP_ROUTES.visaRequirements)}><ArrowLeft size={16} />Back to requirements</button><div className="routes-page__title"><ClipboardCheck size={20} color="#4f83ff" /><h1>{edit ? 'Update Visa Requirement' : 'New Visa Requirement'}</h1></div><p className="routes-page__subtitle">Configure document collection rules for a visa offering.</p></header>
    <form onSubmit={handleSubmit(submit)} className="rounded-xl border border-[#2d282b] bg-[#171314] p-5 shadow-xl"><section className="rounded-xl border border-[#332d30] bg-[#211d20] p-5"><div className="mb-5 flex gap-3"><FileText className="text-blue-200" size={20} /><div><h2 className="font-bold text-white">Document configuration</h2><p className="mt-1 text-sm text-[#8fa0bd]">Choose the visa type and set its document rules.</p></div></div>{loading ? <p className="py-14 text-center text-sm text-[#8fa0bd]">Loading requirement details...</p> : <div className="grid gap-5 md:grid-cols-2"><label className="crud-field md:col-span-2"><span>Visa Type</span><select {...register('visa_type_id', { required: 'Visa type is required.' })}><option value="">Select visa type</option>{visaTypes.map((type) => <option key={type.id} value={String(type.id)}>{optionLabel(type)}</option>)}</select>{errors.visa_type_id && <small>{errors.visa_type_id.message}</small>}</label><label className="crud-field"><span>Document Name</span><input placeholder="e.g. Passport bio page" {...register('document_name', { required: 'Document name is required.', validate: (v) => v.trim() !== '' || 'Document name is required.' })} />{errors.document_name && <small>{errors.document_name.message}</small>}</label><label className="crud-field"><span>Display Order</span><input type="number" min="0" {...register('sort_order', { min: { value: 0, message: 'Order cannot be negative.' } })} />{errors.sort_order && <small>{errors.sort_order.message}</small>}</label><label className="crud-field md:col-span-2"><span>Instructions</span><textarea rows={4} placeholder="Explain acceptable document format or any special conditions." {...register('instructions')} /></label><label className="flex items-start gap-3 rounded-lg border border-[#332d30] bg-[#171314] p-4"><input className="mt-1 h-4 w-4" type="checkbox" {...register('is_required')} /><span><strong className="block text-sm text-white">Required document</strong><small className="mt-1 block text-xs text-[#8fa0bd]">Applicants must supply this document.</small></span></label><label className="flex items-start gap-3 rounded-lg border border-[#332d30] bg-[#171314] p-4"><input className="mt-1 h-4 w-4" type="checkbox" {...register('allow_multiple')} /><span><strong className="block text-sm text-white">Allow multiple uploads</strong><small className="mt-1 block text-xs text-[#8fa0bd]">Applicants can attach more than one file.</small></span></label></div>}</section><footer className="mt-5 flex justify-end gap-3"><button className="crud-button crud-button--ghost" type="button" onClick={() => navigate(APP_ROUTES.visaRequirements)}>Cancel</button><button className="crud-button crud-button--primary" type="submit" disabled={loading || isSubmitting}><Save size={15} />{isSubmitting ? 'Saving...' : 'Save Requirement'}</button></footer></form>
  </div></main>
}
