import { ArrowLeft, Eye, Pencil, Plus, ReceiptText } from 'lucide-react'
import { useCallback, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import AdminDataTable from '../../../components/ui/AdminDataTable'
import { getPackageCostings } from '../service/guidePackagesService'
import { useGuideCollection } from '../hooks/useGuideCollection'

export default function GuidePackageCostingPage() {
  const { id } = useParams(); const navigate = useNavigate(); const [selected, setSelected] = useState(null); const load = useCallback((options) => getPackageCostings(id, options), [id]); const state = useGuideCollection(load, 'Unable to load package costing.')
  const columns = [{ id: 'serial', label: 'SL', width: '72px', render: (_, index) => (state.pagination.from || 0) + index + 1 }, { id: 'type', label: 'Cost Type', accessor: 'cost_type', width: '32%' }, { id: 'amount', label: 'Amount', width: '24%', render: (row) => <span className="font-bold text-emerald-200">৳ {Number(row.cost_amount || 0).toLocaleString()}</span> }, { id: 'date', label: 'Recorded', width: '22%', render: (row) => row.created_at ? new Date(row.created_at).toLocaleDateString() : '-' }]
  return <main className="routes-page"><div className="routes-page__inner"><header className="routes-page__header"><button type="button" className="mb-4 inline-flex items-center gap-2 text-sm font-semibold text-[#8fa0bd] hover:text-white" onClick={() => navigate('/guide/myAssignPackages')}><ArrowLeft size={16} />Assigned packages</button><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="routes-page__title"><ReceiptText size={20} color="#4f83ff" /><h1>Package Costing</h1></div><p className="routes-page__subtitle">Record and review expenses for this package.</p></div><button type="button" className="routes-new-button" onClick={() => navigate(`/guide/my-packageCosting/addCosting/${id}`)}><Plus size={15} />Add Cost</button></div></header><AdminDataTable columns={columns} data={state.items} emptyMessage="No cost entries have been added." isLoading={state.isLoading} onPageChange={state.setPage} onSearchChange={(value) => { state.setPage(1); state.setSearch(value) }} pagination={state.pagination} search={state.search} searchPlaceholder="Search cost type or amount" resultLabel={`${state.pagination.total || state.items.length} cost entries`} rowActionsWidth="100px" renderRowActions={(row) => <div className="flex gap-2"><button className="routes-icon-button" type="button" title="View details" onClick={() => setSelected(row)}><Eye size={15} /></button><button className="routes-icon-button" type="button" title="Edit cost" onClick={() => navigate(`/guide/my-packageCosting/addCosting/${id}/${row.id}`)}><Pencil size={15} /></button></div>} /></div>{selected && <div className="crud-modal" role="dialog"><button className="crud-modal__backdrop" aria-label="Close details" onClick={() => setSelected(null)} /><div className="crud-modal__panel max-w-lg"><header className="crud-modal__header"><div><p className="crud-modal__eyebrow">Cost entry</p><h2>{selected.cost_type}</h2></div><button onClick={() => setSelected(null)}>Close</button></header><div className="space-y-4 p-5 text-sm"><div className="grid grid-cols-2 gap-4"><div><p className="text-[#8fa0bd]">Amount</p><p className="mt-1 font-bold text-white">৳ {selected.cost_amount}</p></div><div><p className="text-[#8fa0bd]">Recorded</p><p className="mt-1 font-bold text-white">{selected.created_at ? new Date(selected.created_at).toLocaleDateString() : '-'}</p></div></div><div><p className="text-[#8fa0bd]">Description</p><p className="mt-1 leading-6 text-white">{selected.description || 'No description provided.'}</p></div></div></div></div>}</main>
}
