import { ArrowLeft, Paperclip, ReceiptText, Save } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { useToast } from '../../../components/common/Toaster'
import { useAuthContext } from '../../../contexts/AuthContext'
import { getCostingById, saveCosting } from '../service/guidePackagesService'

export default function GuidePackageCostingFormPage({ action }) {
  const { packageId, costId } = useParams(); const navigate = useNavigate(); const toast = useToast(); const { auth } = useAuthContext(); const edit = action === 'update'; const [loading, setLoading] = useState(edit); const [saving, setSaving] = useState(false); const [form, setForm] = useState({ cost_type: '', cost_amount: '', description: '', attachment: null })
  useEffect(() => { if (!edit) return; let active = true; (async () => { try { const data = await getCostingById(costId); const item = Array.isArray(data) ? data[0] : data; if (active && item) setForm({ cost_type: item.cost_type || '', cost_amount: item.cost_amount || '', description: item.description || '', attachment: null }) } catch (error) { toast.error(error.message || 'Unable to load costing entry.'); navigate(`/guide/my-packageCosting/${packageId}`) } finally { if (active) setLoading(false) } })(); return () => { active = false } }, [costId, edit, navigate, packageId, toast])
  const submit = async (event) => { event.preventDefault(); try { setSaving(true); const data = new FormData(); data.append('package_id', packageId); data.append('guide_id', auth.user?.id || ''); data.append('cost_type', form.cost_type.trim()); data.append('cost_amount', form.cost_amount); data.append('description', form.description.trim()); if (edit) data.append('costing_id', costId); if (form.attachment) data.append('attachment', form.attachment); await saveCosting(data, edit); toast.success(`Cost entry ${edit ? 'updated' : 'added'} successfully.`); navigate(`/guide/my-packageCosting/${packageId}`) } catch (error) { toast.error(error.message || 'Unable to save costing entry.') } finally { setSaving(false) } }
  const update = (field, value) => setForm((current) => ({ ...current, [field]: value }))
  return <main className="routes-page"><div className="routes-page__inner max-w-4xl"><header className="routes-page__header"><button type="button" className="mb-4 inline-flex items-center gap-2 text-sm font-semibold text-[#8fa0bd] hover:text-white" onClick={() => navigate(`/guide/my-packageCosting/${packageId}`)}><ArrowLeft size={16} />Back to package costing</button><div className="routes-page__title"><ReceiptText size={20} color="#4f83ff" /><h1>{edit ? 'Update Cost Entry' : 'Add Cost Entry'}</h1></div><p className="routes-page__subtitle">Keep a clear expense record for the assigned package.</p></header><form onSubmit={submit} className="rounded-2xl border border-[#2d282b] bg-[#171314] p-5 shadow-xl"><div className="grid gap-5 md:grid-cols-2">{loading ? <p className="col-span-2 py-16 text-center text-[#8fa0bd]">Loading cost entry...</p> : <><label className="crud-field"><span>Cost Type</span><input required value={form.cost_type} onChange={(e) => update('cost_type', e.target.value)} placeholder="e.g. Transport, meals, entry fee" /></label><label className="crud-field"><span>Amount</span><input required min="0" step="0.01" type="number" value={form.cost_amount} onChange={(e) => update('cost_amount', e.target.value)} placeholder="Enter amount" /></label><label className="crud-field md:col-span-2"><span>Description</span><textarea rows={5} value={form.description} onChange={(e) => update('description', e.target.value)} placeholder="Add context for this expense, such as vendor, date, or purpose." /></label><label className="flex cursor-pointer items-center gap-3 rounded-xl border border-dashed border-[#40537a] bg-[#211d20] p-4 md:col-span-2"><Paperclip size={18} className="text-blue-300" /><span className="min-w-0"><strong className="block text-sm text-white">Attach receipt or proof</strong><small className="mt-1 block truncate text-xs text-[#8fa0bd]">{form.attachment?.name || 'Optional: select an image or document.'}</small></span><input className="ml-auto max-w-[180px] text-xs text-[#8fa0bd]" type="file" onChange={(e) => update('attachment', e.target.files?.[0] || null)} /></label></>}</div><footer className="mt-6 flex justify-end gap-3"><button type="button" className="crud-button crud-button--ghost" onClick={() => navigate(`/guide/my-packageCosting/${packageId}`)}>Cancel</button><button type="submit" className="crud-button crud-button--primary" disabled={loading || saving}><Save size={15} />{saving ? 'Saving...' : 'Save Cost Entry'}</button></footer></form></div></main>
}
