export const API_URLS = {
  auth: {
    login: "/login",
  },
  admin: {
    menu: "/admin/menu",
  },
  bookings: {
    invoice: "/admin/booking-invoice",
    list: "/admin/booking",
  },
  dashboard: {
    overview: "/admin/dashboard",
    currentMonthTripSales: "/admin/current-month-trip-sales-report",
    packageProfitMargin: "/admin/package-profit-margin",
  },
  reports: {
    accountBalance: "/admin/accountBalance",
    accountBalanceHistory: (type) => `/admin/accountHistory/${encodeURIComponent(type)}`,
    accountHistorySearch: "/admin/account-history",
    avgBookingValue: "/admin/avg-booking-value-report",
    bookingSummary: "/admin/booking-summary",
    customerValue: "/admin/customerValue",
    dailyBalance: "/admin/monthlyDailyBalanceReport",
    dailyBalanceHistory: "/admin/monthly-daily-balance-reports",
    financialReport: "/admin/financial_report",
    highCancellationPackages: "/admin/high-cancellation-packages",
    lowOccupancyTripReport: "/admin/low-occupancy-trip-report",
    lowPerformingPackages: "/admin/low-performing-packages",
    monitoring: "/admin/monitoring",
    monthRunningBalance: "/admin/monthRunningBalance",
    overallSales: "/admin/overall-sales-summary",
    routeWiseSales: "/admin/route-wise-sales-summary",
    ticketStatusReport: "/admin/ticket-status-report",
    tripPerformance: "/admin/tripPerformance",
    vehicleTracking: "/admin/useageOfVehicle",
    vehicleWiseSeatDetails: (vehicleId) => `/admin/vehiclewiseseat/${vehicleId}`,
    vehicleWiseSeatTotal: "/admin/vehiclewisetotalseat",
  },
  tickets: {
    list: "/admin/tickets",
    update: (ticketId) => `/admin/tickets/update/${ticketId}`,
  },
  refunds: {
    list: "/admin/refund",
    disburse: "/admin/refund/disburse",
  },
  transactions: {
    list: "/admin/transaction",
  },
  resources: {
    guideDropdown: "/admin/guide/dropdown",
    packageCreate: "/admin/packages/create",
    packageDetails: (packageId) => `/packages/${packageId}`,
    packages: "/admin/packages",
    routes: "/admin/routes",
    routeDropdown: "/admin/routes/dropdown",
    visaCountries: "/admin/visa/countries",
    visaCountriesDropdown: "/admin/visa/countries/dropdown",
    visaCountriesUpdate: (countryId) => `/admin/visa/countries/update/${countryId}`,
    visaCountryById: (countryId) => `/admin/visa/countries/${countryId}`,
    visaTypes: "/admin/visa/types",
    visaTypesUpdate: (visaTypeId) => `/admin/visa/types/update/${visaTypeId}`,
    visaTypeById: (visaTypeId) => `/admin/visa/types/${visaTypeId}`,
    vehicles: "/admin/vehicles",
    vehicleDropdown: "/admin/vehicles/dropdown",
    seats: "/admin/seat",
    trips: "/admin/trip",
    tripDropdown: "/admin/trip/dropdown",
    tripSingle: "/admin/single/trip",
    tripSummary: "/admin/tripsummery",
    tripUsers: "/admin/tripwiseBookingUsers",
    tripUpdate: (tripId) => `/admin/trip/update/${tripId}`,
  },
};
