export const APP_ROUTES = {
  avgBookingValueReport: "/admin/avg-booking-value-report",
  bookingSummary: "/admin/bookings/summary",
  dailyBalance: "/admin/account/daily-balance",
  highCancellationPackages: "/admin/high-cancellation-packages",
  lowOccupancyReport: "/admin/low-occupancy-report",
  lowPerformingPackages: "/admin/low-performing-packages",
  monitoring: "/admin/monitoring",
  monthRunningBalance: "/admin/monthRunningBalance",
  packages: "/admin/packages",
  refunds: "/admin/refunds",
  tickets: "/admin/tickets",
  tripPerformance: "/admin/tripPerformance",
  vehicleTrackingReport: "/admin/vehicletrackingreport",
  vehicleWiseSeatReport: "/admin/vehiclewiseseatreport",
  dashboard: "/dashboard",
  routes: "/routes",
  seats: "/seats",
  trips: "/trips",
  vehicles: "/vehicles",
  login: "/login",
};
