export const APP_ROUTES = {
  dailyBalance: "/admin/account/daily-balance",
  lowOccupancyReport: "/admin/low-occupancy-report",
  monthRunningBalance: "/admin/monthRunningBalance",
  packages: "/admin/packages",
  refunds: "/admin/refunds",
  tickets: "/admin/tickets",
  tripPerformance: "/admin/tripPerformance",
  vehicleTrackingReport: "/admin/vehicletrackingreport",
  vehicleWiseSeatReport: "/admin/vehiclewiseseatreport",
  dashboard: "/dashboard",
  routes: "/routes",
  seats: "/seats",
  trips: "/trips",
  vehicles: "/vehicles",
  login: "/login",
};
